from nonebot import on_startswith
from plugins.message_reaction import reaction_cleanup

help = on_startswith("help", ignorecase=False, priority=20, block=True)

@help.handle()
async def handle_function(bot, event):
    cleanup = await reaction_cleanup(bot, event)
    text = (
        "📖 可用命令\n\n"
        "━━━ Steam ━━━━━━━━━━━━━━━\n"
        "id <游戏ID/商店链接>\n"
        "  查游戏详情（steam / 查商店）\n"
        "  例：id 3251240\n\n"
        "pub <发行商名>\n"
        "  查发行商页面截图\n"
        "  例：pub MangoParty\n\n"
        "find <关键字>\n"
        "  搜索 Steam 游戏（搜索steam游戏）\n"
        "  例：find 夫妻\n\n"
        "morepic <游戏ID/商店链接>\n"
        "  发送游戏全部截图缩略图（更多截图）\n"
        "  例：morepic 570\n\n"
        "pending\n"
        "  鉴赏家副本监控，手动检查\n\n"
        "━━━ 挂刀行情 ━━━━━━━━━━━━\n"
        "cs [最低价] [日销量]\n"
        "  CS2 挂刀行情表\n\n"
        "dota [最低价] [日销量]\n"
        "  Dota2 挂刀行情表\n\n"
        "━━━ 登记/记录 ━━━━━━━━━━━━\n"
        "bind\n"
        "  绑定 Steam ID 到 QQ\n\n"
        "get <游戏ID> [用户ID]\n"
        "  登记游戏领取记录\n"
        "  例：get 3251240\n\n"
        "remain <游戏ID> [份数]\n"
        "  剩余份数登记/查询\n"
        "  例：remain 730 5\n\n"
        "wish <游戏ID>\n"
        "  将游戏加入 Steam 愿望单\n\n"
        "report <游戏ID>\n"
        "  标记游戏已报告\n\n"
        "probe\n"
        "  检测领取记录链接是否有效\n\n"
        "unfinished\n"
        "  输出未完成记录\n\n"
        "unreported\n"
        "  输出未报告记录\n\n"
        "queryWishlist <游戏ID>\n"
        "  查询愿望单记录（queryWish / qwish）\n\n"
        "calendar\n"
        "  Steam 个人日历截图（cale / 任务）\n\n"
        "━━━ 工具 ━━━━━━━━━━━━━━━━\n"
        "finder <url>\n"
        "  通用页面截图\n\n"
        "update / pull\n"
        "  手动 git pull 更新并重启\n"
        "update force\n"
        "  强制拉取（丢弃本地更改）后重启\n\n"
        "ping\n"
        "  心跳测试\n\n"
        "help\n"
        "  显示本帮助\n\n"
        "━━━━━━━━━━━━━━━━━━━━━━━\n"
        "💡 直接发 Steam 商店链接也会自动查详情"
    )
    if cleanup: await cleanup()
    await help.finish(text)
